### ISSUE TITLE
What is the Shortcut API URL to access Shortcut story comments?

### ISSUE THREAD

**Issue by ronbarak** [useshortcut/api-cookbook#12]
Using the [Shortcut API](https://developer.shortcut.com/api/rest/v3), I'm trying to find the correct way to get a list of Shortcut Story comments.

However, I'm not sure what would be the correct URL to access the API for a story.

For instance, in the below Python script, **_what should be the_ api_url**?

```
import requests

# Set up the API endpoint and headers
    api_url = 'https://api.shortcut.com/api/v3/MY_COMPANY/stories/10368/comments'
headers = {
    'Shortcut-API-Key': '6412xxxx-xxxx-xxxx-xxxx-xxxx662bf63b',
    'Content-Type': 'application/json'
}

# Make the API request to get the comments for the story
response = requests.get(api_url, headers=headers)

# Check the status code of the response
if response.status_code != 200:
    print('Error:', response.text)
    exit()

# Parse the JSON response and print the comment IDs
comments = response.json()
for comment in comments:
    print(comment['id'])
```

**Comment by ronbarak** [comment]
If I use the api_url as in the format `'https://api.shortcut.com/api/v3/MY_COMPANY/stories/10368/comments'`
I get an error:
`Error: {"message":"Sorry, the organization context for this request is missing. If you have any questions please contact us at support@shortcut.com","tag":"organization2_missing"}`

**Comment by opoku** [comment]
@ronbarak `https://api.app.shortcut.com/api/v3/stories/<story-id>/comments` should work
