### ISSUE TITLE
[Bug]: Print Detailed HTTP Errors

### ISSUE THREAD

**Issue by semperos** [useshortcut/api-cookbook#83]
### Do I have the most recent api-cookbook code?

- [X] I am using the latest code available on the `main` branch of the api-cookbook repo.

### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

At present, when an HTTP request returns a non-2xx, a Python stacktrace is printed, but not the body of the response from the Shortcut API.

### Expected Behavior

The initialize and import scripts should print the JSON response body returned by the Shortcut API when a non-2xx response is returned.

### Minimal Reproducible Example

Pivotal Importer: make one of the imported story's titles exceed the allowed length and view the output.

**Comment by mdthorpe-sc** [comment]
I'm thinking about creating a decorator for lib functions that use Requests.  The basic behaviour would be to trap non-success and print "friendly" errors including payloads. That should cover this requirement

**Comment by mdthorpe-sc** [comment]
https://github.com/useshortcut/api-cookbook/pull/88
