### ISSUE TITLE
Handling API tokens on backend 

### ISSUE THREAD

**Issue by wesley-plutoflume** [useshortcut/api-cookbook#9]
Hi There, 

Apologies if this is not the correct forum. On the CH docs it says that we should include our API tokens as part of the query parameters. Query parameters are generally logged on servers. I can't find any documentation on whether they are logged on POST. Either way I wanted to find out if CH had any special handling for this to protect against tokens being logged in plain text if they are at all.

Thanks in advance :)

**Comment by opoku** [comment]
Sorry for the super late response, but we've transitioned to specifying the token in the request headers using the `Shortcut-Token` header. See our [API docs](https://developer.shortcut.com/api/rest/v3#Authentication).
